- AD
- AE
- AL
- AR
- AT
- AU
- BA
- BE
- BG
- BH
- BR
- CA
- CH
- CN
- CR
- CW
- CY
- CZ
- DE
- DK
- DZ
- EC
- EE
- EG
- ES
- FI
- GB
- GF
- GR
- HK
- HR
- HU
- ID
- IE
- IL
- IT
- JO
- JP
- KE
- KR
- KW
- KZ
- LI
- LK
- LT
- LU
- LV
- MA
- ME
- MG
- MT
- MY
- NL
- 'NO'
- NP
- NZ
- OM
- PH
- PK
- PL
- PR
- PT
- QA
- RO
- RU
- SA
- SE
- SG
- SI
- SK
- SM
- SX
- TH
- TR
- TW
- UA
- US
- AN
- LB
- TN
- AG
- AM
- AO
- AS
- AW
- AZ
- BB
- BD
- BF
- BI
- BJ
- BM
- BN
- BO
- BS
- BW
- BY
- BZ
- CF
- CG
- CI
- CK
- CL
- CM
- CO
- CV
- DJ
- DM
- DO
- ER
- ET
- FJ
- FM
- FO
- GA
- GD
- GE
- GL
- GM
- GT
- GU
- HN
- IN
- IQ
- IS
- JM
- KH
- KI
- KM
- KN
- KP
- LC
- LR
- LY
- MC
- MD
- MH
- MK
- ML
- MO
- MP
- MR
- MV
- MW
- MX
- MZ
- NA
- NE
- NG
- NI
- NR
- PA
- PE
- PG
- PS
- PW
- PY
- RE
- RS
- SB
- SC
- SD
- SN
- SR
- TD
- TG
- TM
- TO
- TP
- TT
- TZ
- UY
- UZ
- VA
- VC
- VE
- VI
- VU
- YE
- ZA
- ZM
- ZW
