visa:
  paymentproductid: 1
  label_key: donate_interface-card-name-visa
  group: cc
  keys: {  }
  logo: card-visa-lg.png
visa-electron:
  paymentproductid: 122
  label_key: donate_interface-card-name-visa
  group: cc
  keys: { }
  logo: card-visa-lg.png
# We need the visa-electron entry in our decoder ring, but we don't want it to
# appear on any forms. Hence we give it an empty country list here. TODO:
# use ReferenceData from SmashPig instead.
  countries: []
visa-debit:
  paymentproductid: 114
  group: cc
  # Same lame trick as visa-electron. ReferenceData still needs a reverse lookup
  # for getPaymentSubmethodMeta
  countries: []
mc-debit:
  paymentproductid: 119
  group: cc
  countries: []
mc:
  paymentproductid: 3
  label_key: donate_interface-card-name-mc
  group: cc
  keys: {  }
  logo: card-mastercard.png
  logo_hd:
    2x: card-mastercard_2x.png
    3x: card-mastercard_3x.png
amex:
  paymentproductid: 2
  label_key: donate_interface-card-name-amex
  group: cc
  keys: {  }
  countries:
    - AD
    - AE
    - AL
    - AR
    - AT
    - AU
    - BA
    - BE
    - BG
    - BH
    - CA
    - CH
    - CN
    - CR
    - CW
    - CY
    - CZ
    - DE
    - DK
    - DZ
    - EC
    - EE
    - EG
    - ES
    - FI
    - GB
    - GR
    - HK
    - HR
    - HU
    - IE
    - IL
# Temporarily disabled 10/7/2016, see T147673
#    - IN
    - IT
    - JO
# Disabled on 2021-07-14 per https://phabricator.wikimedia.org/T286657
#    - JP
    - KE
    - KR
    - KW
    - KZ
    - LI
    - LK
    - LT
    - LU
    - LV
    - MA
    - ME
    - MG
    - MT
    - MY
    - NL
    - 'NO'
    - NP
    - NZ
    - OM
    - PK
    - PL
    - PR
    - PT
    - QA
    - RO
    - RU
    - SA
    - SE
    - SG
    - SI
    - SK
    - SM
    - SX
    - TH
    - TR
    - TW
    - UA
    - US

  logo: card-amex-lg.png
jcb:
  paymentproductid: 125
  label: JCB
  group: cc
  keys: {  }
  countries:
    - AD
    - AT
    - AU
    - BE
    - BH
    - BR
    - DE
    - EC
    - ES
    - FI
    - GB
    - GF
    - GR
    - HK
    - ID
    - IE
    - IT
    - JP
    - KR
    - LU
    - MY
    - NL
    - PH
    - PR
    - PT
    - SG
    - SI
    - SK
    - TH
    - TW
  logo: card-jcb-lg.png
discover:
  paymentproductid: 128
  label_key: donate_interface-card-name-discover
  group: cc
  keys: {  }
  countries:
    - US
  logo: card-discover-lg.png
rtbt_ideal:
  paymentproductid: 809
  label: iDEAL
  group: rtbt
  countries:
    - NL
  validation:
    issuer_id: true
  keys:
    - ISSUERID
  logo: iDEAL-klein.gif
  show_single_logo: true
  issuerids:
    ABNANL2A: ABN Amro
    ASNBNL21: ASN Bank
    # No decision to enable yet.
    #FRBKNL2L: Friesland Bank
    INGBNL2A: ING
    # Disabled for T131181 on 2016-04-05
    #KNABNL2H: Knab
    RABONL2U: Rabobank
    RBRBNL21: RegioBank
    SNSBNL2A: SNS Bank
    TRIONL2U: Triodos Bank
    FVLBNL22: Van Lanschot Bankiers
    BUNQNL2A: bunq
