- AD
- AE
- AL
- AR
- AT
- AU
- BA
- BE
- BG
- BH
- BR
- CA
- CH
- CN
- CR
- CW
- CY
- CZ
- DE
- DK
- DZ
- EC
- EE
- EG
- ES
- FI
- GB
- GF
- GR
- HK
- HR
- HU
- ID
- IE
- IL
- IT
- JO
- JP
- KE
- KR
- KW
- KZ
- LI
- LK
- LT
- LU
- LV
- MA
- ME
- MG
- MT
- MY
- NL
- 'NO'
- NP
- NZ
- OM
- PH
- PK
- PL
- PR
- PT
- QA
- RO
- RU
- SA
- SE
- SG
- SI
- SK
- SM
- SX
- TH
- TR
- TW
- UA
- US
