encryptedCardNumber: encrypted_card_number
encryptedExpiryMonth: encrypted_expiry_month
encryptedExpiryYear: encrypted_expiry_year
encryptedSecurityCode: encrypted_security_code
amount: amount
city: city
country: country
currency: currency
email: email
first_name: first_name
issuer_id: issuer_id
last_name: last_name
order_id: order_id
postal_code: postal_code
return_url: return_url
state_province: state_province
street_address: street_address
user_ip: user_ip
recurring: recurring
# all of the below are for browser fingerprinting, used in 3DSecure
userAgent: user_agent
acceptHeader: accept_header
language: locale
colorDepth: color_depth
screenHeight: screen_height
screenWidth: screen_width
timeZoneOffset: time_zone_offset
javaEnabled: java_enabled
