encryptedCardNumber: card_num
encryptedExpiryMonth: expiration
# HACK HACK HACK, using a totally unrelated field here to not touch API yet
encryptedExpiryYear: processor_form
encryptedSecurityCode: cvv
amount: amount
city: city
country: country
currency: currency
email: email
first_name: first_name
last_name: last_name
order_id: order_id
postal_code: postal_code
state_province: state_province
street_address: street_address
user_ip: user_ip
