<?php

namespace MediaWiki\Extension\DonationInterface\ComboWiki;

use DonationLoggerFactory;
use LogPrefixProvider;
use MediaWiki\Config\Config;
use MediaWiki\Extension\DonationInterface\ComboWiki\Data\DonationDetails;
use MediaWiki\Request\WebRequest;
use Psr\Log\LoggerInterface;
use ReflectionClass;
use SmashPig\Core\DataStores\QueueWrapper;
use SmashPig\Core\SequenceGenerators;
use WhichBrowser\Parser;

class ContributionTrackingHelper implements LogPrefixProvider {
	private string $generatorName = 'contribution-tracking';
	private string $queueName = 'contribution-tracking';

	/**
	 * @var string Key used to store the contribution tracking ID in the DonationDetails object and in the session
	 */
	public static string $contributionTrackingIdKey = 'contribution_tracking_id';
	/**
	 * @var string Key used to store the hash of the current tracking data in the session
	 */
	public string $hashKey = 'ct_hash';

	private WebRequest $request;
	private ?DonationDetails $dataObject;

	private Config $wmfConfig;

	protected LoggerInterface $logger;

	/**
	 * @var string Once defined, store value here for easy access
	 */
	protected string $contributionTrackingId = "";

	public function __construct( WebRequest $request, Config $wmfConfig ) {
		$this->request = $request;
		$this->wmfConfig = $wmfConfig;
		$this->logger = DonationLoggerFactory::getLoggerFromParams( 'ComboWiki', true, false, '', $this );
	}

	/**
	 * Utility function to get or generate a contribution tracking ID.
	 * Returns the value in an array with the key 'id' and a boolean indicating
	 * if the ID was newly generated.
	 *
	 * @return array{id: string, isNew: bool}
	 */
	private function getOrGenerateContributionTrackingId(): array {
		if ( $this->contributionTrackingIdExists() ) {
			$id = $this->dataObject->getValue( $this::$contributionTrackingIdKey );
			$isNew = false;
		} else {
			$id = $this->generateId();
			$isNew = true;
		}
		return [
			'id' => $id,
			'isNew' => $isNew,
		];
	}

	/**
	 * Call from outside to handle contribution tracking data logic. This function will follow these steps:
	 * 1. Get or generate a new contribution_tracking_id if none was found in session already (from $dataObject)
	 * 2. If a new ID was generated, update its value in session and dataObject
	 * 3. It generates $trackingData from dataObject with only the relevant info for the queue
	 * 4. If the trackingData changed (aka current hash is different from the last saved hash),
	 *    push the trackingData to the queue (using sendToContributionTrackingQueue) and update the session ct_hash
	 * @param DonationDetails $dataObject
	 * @return void
	 */
	public function handleTrackingData( DonationDetails $dataObject ): void {
		$this->dataObject = $dataObject;
		$idInfo = $this->getOrGenerateContributionTrackingId();
		$id = $idInfo['id'];

		$this->contributionTrackingId = $id;

		if ( $idInfo['isNew'] ) {
			// A new contribution tracking ID was generated because it was not found in dataObject
			// that is integrated from session
			$this->dataObject->setValue( $this::$contributionTrackingIdKey, $id );
			$this->request->setSessionData( $this::$contributionTrackingIdKey, $id );
		}
		// Now we have the contribution tracking ID, we can generate the tracking data
		$trackingData = $this->getCleanTrackingData();
		$currentHash = sha1( serialize( $trackingData ) );

		if ( $this->trackingDataUpdated( $currentHash ) ) {
			try {
				$id = $this->sendToContributionTrackingQueue( $trackingData, $id );
				$this->logger->info( "Contribution tracking data sent to queue with contribution_tracking_id: $id" );
				$this->request->setSessionData( $this->hashKey, $currentHash );
			} catch ( \Exception $e ) {
				$this->logger->error( 'Failed to push contribution tracking data to queue: ' . $e->getMessage() );
			}

		}
	}

	/**
	 * @return bool True if $dataObject generated by fetching values from the request and session
	 * has already a value set for 'contribution_tracking_id'
	 */
	private function contributionTrackingIdExists(): bool {
		return $this->dataObject->isValueSet( $this::$contributionTrackingIdKey );
	}

	private function generateId(): string {
		$generator = SequenceGenerators\Factory::getSequenceGenerator( $this->generatorName );
		return (string)$generator->getNext();
	}

	private function sendToContributionTrackingQueue( array $tracking_data, ?string $id = null ): string {
		$id = !$id ? $this->generateId() : $id;

		if ( !isset( $tracking_data['ts'] ) || !strlen( $tracking_data['ts'] ) ) {
			$tracking_data['ts'] = wfTimestamp( TS_MW );
		}

		$queueMessage = [
			'id' => $id,
			'ts' => $tracking_data['ts'],
		];

		$queueMessage += $tracking_data;

		QueueWrapper::push( $this->queueName, $queueMessage );

		return $queueMessage['id'];
	}

	/**
	 * @param string $current_hash
	 * @return bool
	 */
	private function trackingDataUpdated( string $current_hash ): bool {
		$last_saved_hash = $this->request->getSessionData( $this->hashKey );
		return $current_hash !== $last_saved_hash;
	}

	/**
	 * Clean array of tracking data to contain valid fields
	 *
	 * Compares tracking data array to list of valid tracking fields and
	 * removes any extra tracking fields/data.  Also sets empty values to
	 * 'null' values.
	 * @param bool $unset If set to true, empty values will be unset from the
	 * return array, rather than set to null. (default: false)
	 * @return array Clean tracking data
	 */
	private function getCleanTrackingData( bool $unset = false ): array {
		// define valid tracking fields
		$trackingFields = [
			'amount',
			'appeal',
			'app_install_id',
			'country',
			'currency',
			'gateway',
			'landing_page',
			'language',
			'payment_method',
			'payment_submethod',
			'referrer',
			'ts',
			'utm_campaign',
			'utm_key',
			'utm_medium',
			'utm_source',
		];

		$tracking_data = [];

		foreach ( $trackingFields as $value ) {
			if ( $this->dataObject->isValueSet( $value ) ) {
				$tracking_data[$value] = $this->dataObject->getValue( $value );
			} else {
				if ( !$unset ) {
					$tracking_data[$value] = null;
				}
			}
		}

		// TODO: check if this should move to DataIntegrator since it fetches values from the request
		// Add OS and browser, plus major version numbers of each if available
		$headers = $this->request->getAllHeaders();
		$parser = new Parser( $headers );
		$tracking_data = array_merge( $tracking_data, [
			'browser' => $parser->browser->getName(),
			'browser_version' => preg_replace( '/[^0-9].*/', '', $parser->browser->getVersion() ),
			'os' => $parser->os->getName(),
			// For versions, discard everything after the first non-digit
			'os_version' => preg_replace( '/[^0-9].*/', '', $parser->os->getVersion() ),
		] );

		// Variant is the new way to a/b test forms. Appeal is still used to
		// render wikitext at the side, but it's almost always JimmyQuote
		if ( $this->dataObject->isValueSet( 'variant' ) ) {
			$tracking_data['payments_form_variant'] = $this->dataObject->getValue( 'variant' );
		}
		if ( $this->dataObject->getValue( 'recurring' ) === '1' ) {
			$tracking_data['is_recurring'] = 1;
		}

		// Add banner history log id if sent and enabled
		if ( $this->dataObject->isValueSet( 'bannerhistlog' ) ) {
			if ( $this->wmfConfig->has( 'EnableBannerHistoryLog' ) && $this->wmfConfig->get( 'EnableBannerHistoryLog' ) ) {
				$tracking_data['banner_history_log_id'] = $this->dataObject->getValue( 'bannerhistlog' );
			}
		}
		return $tracking_data;
	}

	public function getLogMessagePrefix(): string {
		$thisClassName = ( new ReflectionClass( $this ) )->getShortName();
		$contributionTrackingId = $this->contributionTrackingId;
		return "$thisClassName:$contributionTrackingId ";
	}
}
