# Taken from https://developer.paypal.com/reference/currency-codes/#paypal-account-payments for braintree paypal
- AUD # Australian Dollar
#- BRL # Brazilian real 2
- CAD # Canadian Dollar
- CHF # Swiss Franc
#- CNY # Chinese Renmenbi Yuan 3 (Not supported from braintree paypal account )
- CZK # Czech Koruna
- DKK # Danish Krone
- EUR # Euro
- GBP # British Pound
- HKD # Hong Kong dollar
- HUF # Hungarian forint 1
- ILS # Israeli new shekel
- JPY # Japanese yen 1
- MXN # Mexican Peso
#- MYR # Malaysian Ringgit 3
- NOK # Norwegian Krone
- NZD # New Zealand Dollar
- PHP # Philippine Peso
- PLN # Polish Złoty
- RUB # Russian ruble
- SEK # Swedish Krona
- SGD # Singapore Dollar
- THB # Thai Baht
- TWD # New Taiwan Dollar 1
- USD # United States Dollar

# 1 This currency does not support decimals. If you pass a decimal amount, an error occurs.
# 2 This currency is supported as a payment currency and a currency balance for in-country PayPal accounts only. If the receiver of funds is not from Brazil, then PayPal converts funds into the primary holding currency of the account with the applicable currency conversion rate. The currency conversion rate includes PayPal's applicable spread or fee.
# 3 This currency is supported as a payment currency and a currency balance for in-country PayPal accounts only.
