<?php namespace DonationForm;

/**
 * Interface to our payment method and gateway configuration.
 */
class Configuration {
	public function getNationalCurrency( $country ) {
		$currencyMap = ConfigReference::getCurrencyMap();
		if ( array_key_exists( $country, $currencyMap ) ) {
			return $currencyMap[$country];
		}
		return "USD";
	}

	public function getAvailablePaymentMethods( $country, $currency, $recurring ) {
		//FIXME
		return array( 'cc' );
	}
}

/**
 * TODO: These rules will be moved into a database, and this class eliminated.
 */
class ConfigReference {
	static public function getCurrencyMap() {
		return array(
			'AD' => "EUR",
			'AE' => "AED",
			'AF' => "USD",
			'AG' => "XCD",
			'AL' => "EUR",
			'AM' => "EUR",
			'AN' => "ANG",
			'AO' => "USD",
			'AR' => "ARS",
			'AS' => "USD",
			'AT' => "EUR",
			'AU' => "AUD",
			'AW' => "EUR",
			'AZ' => "EUR",
			'BA' => "EUR",
			'BB' => "BBD",
			'BD' => "BDT",
			'BE' => "EUR",
			'BF' => "XOF",
			'BG' => "BGN",
			'BH' => "BHD",
			'BI' => "USD",
			'BJ' => "XOF",
			'BM' => "BMD",
			'BN' => "USD",
			'BO' => "BOB",
			'BR' => "BRL",
			'BS' => "BSD",
			'BW' => "USD",
			'BY' => "EUR",
			'BZ' => "BZD",
			'CA' => "CAD",
			'CF' => "XAF",
			'CG' => "USD",
			'CH' => "CHF",
			'CI' => "EUR",
			'CK' => "NZD",
			'CL' => "CLP",
			'CM' => "XAF",
			'CN' => "CNY",
			'CO' => "COP",
			'CR' => "CRC",
			'CV' => "USD",
			'CY' => "EUR",
			'CZ' => "CZK",
			'DE' => "EUR",
			'DJ' => "USD",
			'DK' => "DKK",
			'DM' => "XCD",
			'DO' => "DOP",
			'DZ' => "DZD",
			'EC' => "USD",
			'EE' => "EUR",
			'EG' => "EGP",
			'ER' => "USD",
			'ES' => "EUR",
			'ET' => "USD",
			'FI' => "EUR",
			'FJ' => "FJD",
			'FM' => "USD",
			'FO' => "DKK",
			'FR' => "EUR",
			'GA' => "XAF",
			'GB' => "GBP",
			'GD' => "XCD",
			'GE' => "USD",
			'GF' => "EUR",
			'GL' => "DKK",
			'GM' => "USD",
			'GQ' => "USD",
			'GR' => "EUR",
			'GT' => "GTQ",
			'GU' => "USD",
			'GW' => "USD",
			'HK' => "HKD",
			'HN' => "HNL",
			'HR' => "HRK",
			'HU' => "HUF",
			'ID' => "IDR",
			'IE' => "EUR",
			'IL' => "ILS",
			'IN' => "INR",
			'IQ' => "USD",
			'IS' => "USD",
			'IT' => "EUR",
			'JM' => "JMD",
			'JO' => "JOD",
			'JP' => "JPY",
			'KE' => "KES",
			'KH' => "USD",
			'KI' => "AUD",
			'KM' => "USD",
			'KN' => "XCD",
			'KP' => "USD",
			'KR' => "KRW",
			'KW' => "USD",
			'KZ' => "KZT",
			'LB' => "LBP",
			'LC' => "XCD",
			'LI' => "CHF",
			'LK' => "LKR",
			'LR' => "USD",
			'LT' => "LTL",
			'LU' => "EUR",
			'LV' => "LVL",
			'LY' => "EUR",
			'MA' => "MAD",
			'MC' => "EUR",
			'MD' => "USD",
			'ME' => "EUR",
			'MG' => "EUR",
			'MH' => "USD",
			'MK' => "MKD",
			'ML' => "XOF",
			'MO' => "USD",
			'MP' => "USD",
			'MR' => "USD",
			'MT' => "EUR",
			'MU' => "USD",
			'MV' => "MVR",
			'MW' => "GBP",
			'MX' => "MXN",
			'MY' => "MYR",
			'MZ' => "USD",
			'NA' => "USD",
			'NE' => "XOF",
			'NG' => "USD",
			'NI' => "NIO",
			'NL' => "EUR",
			'NO' => "NOK",
			'NP' => "INR",
			'NR' => "AUD",
			'NZ' => "NZD",
			'OM' => "OMR",
			'PA' => "PAB",
			'PE' => "PEN",
			'PG' => "AUD",
			'PH' => "PHP",
			'PK' => "PKR",
			'PL' => "PLN",
			'PR' => "USD",
			'PS' => "USD",
			'PT' => "EUR",
			'PW' => "USD",
			'PY' => "PYG",
			'QA' => "QAR",
			'RE' => "EUR",
			'RO' => "RON",
			'RS' => "EUR",
			'RU' => "RUB",
			'SA' => "SAR",
			'SB' => "USD",
			'SC' => "SCR",
			'SD' => "GBP",
			'SE' => "SEK",
			'SG' => "SGD",
			'SI' => "EUR",
			'SK' => "EUR",
			'SM' => "EUR",
			'SN' => "XOF",
			'SR' => "EUR",
			'SV' => "USD",
			'TD' => "XAF",
			'TG' => "XOF",
			'TH' => "THB",
			'TM' => "RUB",
			'TN' => "TND",
			'TO' => "USD",
			'TP' => "USD",
			'TR' => "TRY",
			'TT' => "TTD",
			'TW' => "TWD",
			'TZ' => "USD",
			'UA' => "UAH",
			'US' => "USD",
			'UY' => "UYU",
			'UZ' => "RUB",
			'VA' => "EUR",
			'VC' => "USD",
			'VE' => "USD",
			'VI' => "USD",
			'VN' => "VND",
			'VU' => "AUD",
			'YE' => "USD",
			'ZA' => "ZAR",
			'ZM' => "USD",
			'ZW' => "USD",
		);
	}
}
