# Taken from https://docs.dlocal.com/reference/country-reference
- AR
- BD
- BO
- BR
- CI
- CL
- CM
- CN
- CO
- CR
- DO
- EC
- EG
- GH
- GT
- HN
- ID
- IN
- JP
- KE
- MA
- MX
- MY
- NG
- NI
- PA
- PE
- PH
- PK
- PY
- RW
- SN
- SV
- TH
- TR
- TZ
- UG
- US
- UY
- VN
- ZA
