# See https://docs.dlocal.com/reference/country-reference
- ARS # Argentina
- BDT # Bangladesh
- BOB # Bolivia
- BRL # Brazil
- CFA # Ivory Coast
- CLP # Chile
- CNY # China
- COP # Colombia
- CRC # Costa Rica
- DOP # Dominican Republic
- EGP # Egypt
- GHS # Ghana
- GTQ # Guatemala
- HNL # Honduras
- IDR # Indonesia
- INR # India
- KES # Kenya
- MAD # Morocco
- MXN # Mexico
- MYR # Malaysia
- NGN # Nigeria
- NIO # Nicaragua
- PEN # Peru
- PHP # Philippines
- PKR # Pakistan
- PYG # Paraguay
- RWF # Rwanda
- THB # Thailand
- TRY # Turkey
- TZS # Tanzania
- UGX # Uganda
- USD # Ecuador, El Salvador & Panama
- UYU # Uruguay
- VND # Vietnam
- XAF # Cameroon
- XOF # Senegal
- YEN # Japan
- ZAR # South Africa
