# This is a combination of all the countries that are supported by Adyen, dLocal and I think PayPal.
- AD  # Andorra
- AG  # Antigua and Barbuda
- AI  # Anguilla
- AL  # Albania
- AM  # Armenia
- AO  # Angola
- AQ  # Antartica
- AR  # Argentina
- AS  # American Samoa
- AT  # Austria
- AU  # Australia
- AW  # Aruba
- AX  # Åland Islands
- AZ  # Azerbaijan
- BA  # Bosnia and Herzegovina
- BB  # Barbados
- BD  # Bangladesh
- BE  # Belgium
- BG  # Bulgaria
- BH  # Bahrain
- BI  # Burundi
- BL  # Saint Barthélemy
- BM  # Bermuda
- BN  # Brunei Darussalam
- BO  # Bolivia
- BR  # Brazil
- BS  # Bahamas
- BT  # Bhutan
- BV  # Bouvet Island
- BZ  # Belize
- CA  # Canada
- CC  # Cocos (Keeling) Islands
- CH  # Switzerland
- CK  # Cook Islands
- CI  # Côte d'Ivoire
- CL  # Chile
- CM  # Cameroon
- CN  # China
- CO  # Colombia
- CR  # Costa Rica
- CV  # Cabo Verde
- CW  # Curaçao
- CX  # Christmas Island
- CY  # Cyprus
- CZ  # Czech Republic
- DE  # Germany
- DK  # Denmark
- DM  # Dominica
- DO  # Dominican Republic
- DZ  # Algeria
- EC  # Ecuador
- EE  # Estonia
- EG  # Egypt
- ES  # Spain
- FJ  # Fiji
- FK  # Falkland Islands (Malvinas)
- FM  # Micronesia, Federated States of
- FO  # Faroe Islands
- FR  # France
- GB  # United Kingdom
- GD  # Grenada
- GE  # Georgia
- GF  # French Guiana
- GG  # Guernsey
- GH  # Ghana
- GI  # Gibraltar
- GL  # Greenland
- GP  # Guadeloupe
- GR  # Greece
- GS  # South Georgia and the South Sandwich Islands
- GT  # Guatemala
- GU  # Guam
- GY  # Guyana
- HK  # Hong Kong
- HM  # Heard Island and McDonald Islands
- HN  # Honduras
- HK  # Hong Kong
- HR  # Croatia
- HT  # Haiti
- HU  # Hungary
- ID  # Indonesia
- IE  # Ireland
- IL  # Israel
- IM  # Isle of Man
- IO  # British Indian Ocean Territory
- IN  # India
- IS  # Iceland
- IT  # Italy
- JM  # Jamaica
- JO  # Jordan
- JP  # Japan
- KE  # Kenya
- KH  # Cambodia
- KI  # Kiribati
- KM  # Comoros
- KN  # Saint Kitts and Nevis
- KW  # Kuwait
- KZ  # Kazakhstan
- LC  # Saint Lucia
- LI  # Liechtenstein
- LK  # Sri Lanka
- LR  # Liberia
- LT  # Lithuania
- LU  # Luxembourg
- LV  # Latvia
- MA  # Morocco
- MC  # Monaco
- ME  # Montenegro
- MF  # Saint Martin
- MH  # Marshall Islands
- MK  # North Macedonia
- MN  # Mongolia
- MO  # Macao
- MP  # Northern Mariana Islands
- MQ  # Martinique
- MS  # Montserrat
- MT  # Malta
- MV  # Maldives
- MX  # Mexico
- MY  # Malaysia
- NE  # Niger
- NF  # Norfolk Island
- NG  # Nigeria
- NI  # Nicaragua
- NL  # Netherlands
- 'NO'  # Norway
- NP  # Nepal
- NR  # Nauru
- NU  # Niue
- NZ  # New Zealand
- OM  # Oman
- PA  # Panama
- PE  # Peru
- PF  # French Polynesia
- PH  # Philippines
- PK  # Pakistan
- PL  # Poland
- PM  # Saint Pierre and Miquelon
- PN  # Pitcairn
- PR  # Puerto Rico
- PS  # Palestine
- PT  # Portugal
- PW  # Palau
- PY  # Paraguay
- QA  # Qatar
- RE  # Réunion
- RO  # Romania
- RS  # Serbia
- RW  # Rwanda
- SE  # Sweden
- SG  # Singapore
- SH  # Saint Helena, Ascension and Tristan da Cunha
- SI  # Slovenia
- SJ  # Svalbard and Jan Mayen
- SK  # Slovakia
- SM  # San Marino
- SN  # Senegal
- SR  # Suriname
- SV  # El Salvador
- SX  # Sint Maarten
- TC  # Turks and Caicos Islands
- TD  # Chad
- TF  # French Southern Territories
- TH  # Thailand
- TJ  # Tajikistan
- TK  # Tokelau
- TL  # Timor-Leste
- TR  # Turkey
- TT  # Trinidad and Tobago
- TV  # Tuvalu
- TW  # Taiwan
- TZ  # Tanzania
- UA  # Ukraine
- UG  # Uganda
- UM  # United States Minor Outlying Islands
- US  # United States
- UY  # Uruguay
- VA  # Vatican City
- VC  # Saint Vincent and the Grenadines
- VE  # Venezuela
- VG  # Virgin Islands (British)
- VI  # Virgin Islands (U.S.)
- VN  # Vietnam
- VU  # Vanuatu
- WF  # Wallis and Futuna
- WS  # Samoa
- YT  # Mayotte
- ZA  # South Africa
