# TODO: this is a copy of our existing adyen countries as we'll be using adyen first via gravy.
# However, once we add additional gateways, we might need to update this list.
- AU
- AG
- AT
- BD
- BE
- BG
- BH
- BM
- BO
- BZ
- CA
- CH
- CN
- CR
- CZ
- DE
- DK
- DM
- DO
- DZ
- EG
- ES
- FJ
- FR
- GB
- GD
- GR
- GT
- HN
- HK
- HR
- HU
- IE
- IL
- IT
- JM
- JO
- JP
- KE
- KW
- KZ
- LI
- LK
- LU
- LV
- MA
- MK
- MY
- NL
- NO
- NZ
- OM
- PA
- PH
- PK
- PL
- PS
- PT
- QA
- SE
- SG
- SK
- RO
- TH
- TT
- TW
- UA
- US
