# This is a combination Adyen, dLocal & PayPal supported payment methods
cc:
  is_default: true
  recurring: true
  label: Credit Cards
  validation:
    country: true
    name: true
    email: true

dd:
  recurring: true
  label: Direct debit
  validation:
    country: false
    address: false
    street_address: false
    postal_code: false
    name: false
    email: true
    trustly_explanation: true

rtbt:
  recurring: false
  label: Real time bank transfer
  validation:
    country: true
    name: true
    email: true

bt:
  recurring: true  # Changed from false to true based on dlocal config
  label: Bank Transfer
  validation:
    country: true
    name: true
    email: true
    payment_submethod: true  # Added from dlocal

venmo:
  recurring: false
  validation:
    country: true
    name: true
    email: true
  countries:
    - US

paypal:
  recurring: true
  validation:
    country: false
    address: false
    street_address: false
    postal_code: false

google:
  recurring: true
  label: Google Pay
  validation:
    country: false
    address: false
    street_address: false
    postal_code: false

apple:
  recurring: true
  label: Apple Pay
  validation:
    country: false
    address: false
    street_address: false
    postal_code: false

cash:
  recurring: false  # Added from dlocal
  validation:
    country: true
    name: true
    email: true
    payment_submethod: false  #Added from dlocal
