# This is a combination of Adyen, dLocal & PayPal supported payment submethods
cb:
  countries:
    - FR
  group: cc

ach:
  label: ACH
  group: dd
  countries:
    - US
    - ZA
  logo: bank-ach.png
  logo_hd:
    2x: bank-ach_2x.png
    3x: bank-ach_3x.png

visa:
  group: cc
  countries:
    - AR
    - AU
    - BR
    - CA
    - CL
    - CO
    - FR
    - GB
    - IE
    - IL
    - IN
    - JP
    - MX
    - NL
    - NZ
    - PE
    - SE
    - UA
    - UY
    - US
    - ZA
  recurring: true

visa-debit:
  group: cc
  countries:
    - AR
    - BR
    - CL
    - CO
    - IN
    - MX
    - PE
    - UY
    - ZA
  recurring: true

maestro:
  group: cc
  countries:
    - BE
    - RO
    - AR
    # - BR
    # - IN
  recurring: true

mc:
  group: cc
  countries:
    - AR
    - AU
    - BR
    - CA
    - CL
    - CO
    - FR
    - GB
    - IE
    - IL
    - IN
    - JP
    - MX
    - NL
    - NZ
    - PE
    - SE
    - UA
    - UY
    - US
    - ZA
  recurring: true

amex:
  group: cc
  countries:
    - AR
    - AU
    - CA
    - FR
    - GB
    - IE
    - IL
    - JP
    - NL
    - NZ
    - SE
    - UA
    - US
    - AR
    - BR
    - CL
    - CO
    # - IN // Dlocal reported that AMEX is not supported in India T334945, and all other commentted out methods can be enabled by ask
    - MX
    - PE
    - ZA
  recurring: true

jcb:
  group: cc
  countries:
    - AU
    - IE
    - JP
    - NL
    - BR

discover:
  group: cc
  countries:
    - IL
    - US
    - BR
  recurring: true

rtbt_ideal:
  group: rtbt
  countries:
    - NL

onlineBanking_CZ:
  group: bt
  countries:
    - CZ

sepadirectdebit:
  group: rtbt
  countries:
    - AT
    - BE
    - DE
    - EE
    - ES
    - FR
    - GR
    - HR
    - IE
    - IT
    - LT
    - LU
    - LV
    - MT
    - NL
    - PT
    - SI
    - SK
  recurring: true

interac:
  group: cc

#argen:
#  group: cc
#  countries:
#    - AR

banco_do_brasil:
  group: bt
  countries:
    - BR
  logo: bank-banco_do_brasil.png

bradesco:
  group: bt
  countries:
    - BR
  logo: bank-bradesco.png

#bbva:
#  label: BBVA
#  group: bt
#  countries:
#    - PE
#  logo: bank-bbva.png
#  logo_hd:
#    2x: bank-bbva_2x.png
#    3x: bank-bbva_3x.png

bcp:
  label: BCP
  group: bt
  countries:
    - PE
  logo: bank-bcp.png
  logo_hd:
    2x: bank-bcp_2x.png
    3x: bank-bcp_3x.png

cabal:
  group: cc
  countries:
    - AR
  recurring: true

cabal-debit:
  group: cc
  countries:
    - AR
  recurring: true

#bancolombia:
#  label: Bancolombia
#  group: cash
#  countries:
#  - CO
#  logo: bank-bancolombia.png

#carnet:
#  group: cc
#  countries:
#  - MX
#  recurring: true

#carnet_debit:
#  group: cc
#  countries:
#  - MX
#  recurring: true

#carulla:
#  label: Carulla
#  group: cash
#  countries:
#  - CO
#  logo: cash-carulla.png

cash_abitab:
  label: Abitab
  group: cash
  countries:
    - UY
  logo: cash-abitab.png
  logo_hd:
    2x: cash-abitab_2x.png
    3x: cash-abitab_3x.png

cash_boleto:
  label: Boletos
  group: cash
  countries:
    - BR
  logo: bank-boleto.png

cash_efecty:
  label: Efecty
  group: cash
  countries:
    - CO
  logo: cash-efecty.png

cash_oxxo:
  label: OXXO
  group: cash
  countries:
    - MX
  logo: cash-oxxo.png

cash_pago_efectivo:
  label: Pago Efectivo
  group: cash
  countries:
    - PE
  logo: cash-pago-efectivo.png

#cash_pago_facil:
#  label: Pago Facil
#  group: cash
#  countries:
#  - AR
#  logo: cash-pago-facil.png

cash_rapipago:
  label: Rapi Pago
  group: cash
  countries:
    - AR
  logo: cash-rapipago.png

cash_red_pagos:
  label: Red Pagos
  group: cash
  countries:
    - UY
  logo: cash-red-pagos.png

#cencosud:
#  group: cc
#  countries:
#    - AR
#  recurring: true

cmr:
  group: cc
  countries:
    - CL
  recurring: true

#codenza:
#  group: cc
#  countries:
#  - CO
#  recurring: true

#codi:
#  label: Codi Bank Transfer Online
#  group: bt
#  countries:
#  - MX
#  logo: bank-codi.png

#codi_qr:
#  label: Codi Bank Transfer QR
#  group: bt
#  countries:
#  - MX
#  logo: bank-codi.png

#cordobesa:
#  group: cc
#  countries:
#    - AR
#  recurring: true

#debin:
#  label: DEBIN
#  group: bt
#  countries:
#  - AR
#  logo: bank-debin.png

diners:
  group: cc
  countries:
    - AR
    - CL
    - CO
    # - IN
    - PE
    - UY
  recurring: true

elo:
  group: cc
  countries:
    - BR
  recurring: true

elo-debit:
  group: cc
  countries:
    - BR

hiper:
  group: cc
  countries:
    - BR
  recurring: true

#interbank:
#  label: Interbank
#  group: bt
#  countries:
#    - PE
#  logo: bank-interbank.png
#  logo_hd:
#    2x: bank-interbank_2x.png
#    3x: bank-interbank_3x.png

itau:
  label: Itau
  group: bt
  countries:
    - BR
  logo: bank-itau.png

lider:
  group: cc
  countries:
    - UY
  recurring: true

mach:
  group: cc
  countries:
    - CL
  recurring: true

magna:
  group: cc
  countries:
    - CL
  recurring: true

mc-debit:
  group: cc
  countries:
    - AR
    - BR
    - CL
    - CO
    - IN
    - MX
    - PE
    - UY
    - ZA
  recurring: true

naranja:
  group: cc
  countries:
    - AR
  recurring: true

#nativa:
#  group: cc
#  countries:
#    - AR
#  recurring: true

netbanking:
  label_key: donate_interface-bank-name-netbanking
  group: bt
  countries:
    - IN
  logo: bank-netbanking.png
  logo_hd:
    2x: bank-netbanking_2x.png
  recurring: false

oca:
  group: cc
  countries:
    - UY
  recurring: true

#picpay:
#  label: PicPay
#  group: bt
#  countries:
#  - BR
#  logo: bank-picpay.png

pix:
  label: Pix
  group: cash
  countries:
    - BR
  logo: bank-pix.png

presto:
  group: cc
  countries:
    - CL
  recurring: true

pse:
  label: PSE
  group: bt
  countries:
    - CO
  logo: bank-pse.png

#puntored:
#  label: Puntored
#  group: cash
#  countries:
#  - CO
#  logo: bank-puntored.png

rupay:
  group: cc
  countries:
    - IN

santander:
  label: Santander
  group: bt
  countries:
    - BR
  logo: bank-santander.png

#santander_rio:
#  label: Santander
#  group: bt
#  countries:
#    - AR
#  logo: bank-santander.png

servipag:
  label: Servipag
  group: cash
  countries:
    - CL
  logo: cash-servipag.png

#sencillito:
#  label: Sencillito
#  group: cash
#  countries:
#  - CL
#  logo: cash-sencillito.png

#shopping:
#  group: cc
#  countries:
#    - AR

#spei:
#  label: SPEI
#  group: bt
#  countries:
#  - MX
#  logo: bank-spei.png

stitch:
  label: Stitch
  group: bt
  countries:
    - ZA
  logo: bank-ach.png

upi:
  label: UPI
  group: bt
  countries:
    - IN
  logo: bank-upi.png
  logo_hd:
    2x: bank-upi_2x.png
  recurring: true
  show_single_logo: true

webpay:
  group: bt
  countries:
    - CL
  logo: bank-webpay.png
