# Core
- Amount
- CountryValidation
- FiscalNumber
- PlaceholderFiscalNumber
- PlaceholderPhoneNumber
- PostalCodeValidation
- ReturnUrl
- Simple3DSecure  # sets use_3d_secure
- Gravy3DSecure  # sets browser info parameters
- StreetAddressValidation
- StreetNumberValidation
