gateway_session_id: gateway_session_id
amount: amount
city: city
country: country
currency: currency
email: email
first_name: first_name
last_name: last_name
order_id: order_id
phone: phone
postal_code: postal_code
state_province: state_province
user_ip: user_ip
recurring: recurring
street_address: street_address
street_number: street_number
fiscal_number: fiscal_number
gateway_txn_id: gateway_txn_id
payment_method: payment_method
payment_submethod: payment_submethod
return_url: return_url
use_3d_secure: use_3d_secure
gateway_donor_id: gateway_donor_id
user_name: user_name
card_suffix: card_suffix
card_scheme: card_scheme
payment_token: payment_token
full_name: full_name