amount: amount
cancel_url: cancel_url
currency: currency
date: date
description: description
email: email
frequency_unit: frequency_unit
gateway_session_id: gateway_session_id
language: language
order_id: order_id
processor_contact_id: processor_contact_id
recurring: recurring
return_url: return_url
