# Skip AmountInCents.
- Amount
- AstroPayFinancialNumbers
- AstroPayMethodCodec
- CountryValidation
- DonorEmail
- FiscalNumber
- PlaceholderFiscalNumber # see class comment
- DonorFullName
- StreetAddress
# Signature calculation must come last
- AstroPaySignature
